baseURL = 'https://montagna-katokeyci.github.io/'
languageCode = 'ja'
title = 'Montagna 山行記録'
theme = 'PaperMod'

[params]
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

[taxonomies]
  category = 'categories'
  tag = 'tags'

[[menu.main]]
  name = "カテゴリ一覧"
  url = "/categories/"
  weight = 10

[[menu.main]]
  name = "タグ一覧"
  url = "/tags/"
  weight = 20